### ISSUE TITLE
player struggles with very short loops

### ISSUE THREAD

**Issue by danieljamesross** [pkalogiros/AudioMass#6] opened 2020-05-28 15:55 UTC
Great product, congrats.

Small bug, when you try to loop a selection that is only a few milliseconds long, the playbar can sometimes jump past the loop end point, breaking out of the loop.

**Comment by pkalogiros** [comment] 2020-06-05 18:26
Thanks for your kind words!
The issue is in the wavesurfer regions plugin (my plan is to remove anything wavesurfer related)

`if (!_this3.firedOut && _this3.firedIn && (_this3.start >= Math.round(time * 100) / 100 || _this3.end <= Math.round(time * 100) / 100)) {`

Due to the round conversions, the values get truncated and it passes through.
A fix has been pushed at - https://github.com/pkalogiros/AudioMass/pull/21/commits/7e9ab69cc07fe3cae65358261bd77507ab50f0b8

Will be pushing on audiomass.co later today

**Comment by pkalogiros** [comment] 2020-06-09 18:07
Will be closing this issue. Feel free to re-open if things are not right.

**Closed by pkalogiros** 2020-06-09 18:07 UTC
